### ISSUE TITLE
[devel] Battery value onGameOver screen only is showed one time

### ISSUE THREAD

**Issue by hpsaturn** [hpsaturn/esp32-atari-game-breakout#2]
After the first setup and first game over state, the battery status works fine, in the next game over cases, it didn't work again. Only in branch #1

**Comment by ygator** [comment]
You have two issues with the battery status.  One is that you are doing the analogRead(ADC_PIN) too quickly after doing the digitalWrite(ADC_EN, HIGH).  You must put a small delay between the two and delay(10) seems to work find.
The second issue is when the battery percentage is displayed setTextDatum should be set to TL_DATUM before the drawstring for batt is done.

**Comment by hpsaturn** [comment]
Thanks man, I'll try to do it or you prefer send me a pull request?

**Comment by hpsaturn** [comment]
Thanks @ygator for the issue fix, it was merged in the PR #4
